---
title: "PHOT 301: Quantum Photonics"
subtitle: "Problems and final answers of 1.1, 1.2, 1.3, 1.5, 1.8"
author: "Michaël Barbier"
#date: today
#date-format: long
execute:
  echo: true
  output: true
  warning: true
  error: true
  code-overflow: wrap
  code:
    font-size: 48px
  code-line-numbers: true
format: 
  pdf:
    include-in-header:
      text:
        \usepackage{amsfonts}
        \usepackage{amsmath}
        \DeclareMathOperator\erf{erf}
    highlight-style: tango
    documentclass: scrartcl
    papersize: A4
    fontsize: 12pt
    margin-bottom: 2.5cm
    margin-top: 2.5cm
    margin-left: 2.5cm
    margin-right: 2.5cm
editor: source
jupyter: python3
---


# Problems

Here we list the problems with there final solutions so you can check whether you have the corrects answers. Some problems ask you to prove a theorem, for these problems, I write just some extra hints.
The problems are from Griffiths 3rd edition. The problems for this week:

- Chapter 1: 1.1, 1.2, 1.3, 1.5, 1.8

## Problem 1.1
\color{Black}

For the distribution of ages in the example in Section 1.3.1:

(a) Compute $\langle j^2\rangle$ and $\langle j \rangle^2$.
(b) Determine $\Delta j$ for each $j$, and use Equation 1.11 to compute the standard deviation.
(c) Use your results in (a) and (b) to check Equation 1.12.

### Solution (1.1)
\color{Blue}

(a) $\langle j^2\rangle = 459.6$ and $\langle j \rangle^2 = 441$.
(b) Standard deviation $\sigma = 4.3$.
(c) $4.3 = \langle (\Delta j)^2 \rangle = \sqrt{18.6}$?


## Problem 1.2
\color{Black}

(a) Find the standard deviation of the distribution in Example 1.2.
(b) What is the probability that a photograph, selected at random, would show a
distance x more than one standard deviation away from the average?

### Solution (1.2)
\color{Blue}

(a) Standard deviation $\sigma = \frac{2}{3\sqrt{5}}\,h$.
(b) $1 - \sqrt{\frac{1}{3}(1 + 2/\sqrt{5})} +  \sqrt{\frac{1}{3}(1 - 2/\sqrt{5})}$.

## Problem 1.3
\color{Black}

Consider the gaussian distribution
$$
\rho(x) = A e^{-\lambda(x - a)^2},
$$

where $A$, $a$, and $\lambda$ are positive real constants. (The necessary integrals are inside the back cover.)

(a) Use Equation 1.16 to determine $A$.
(b) Find $\langle x \rangle$, $\langle x^2 \rangle$, and $\sigma$.
(c) Sketch the graph of $\rho(x)$.

### Solution (1.3)
\color{Blue}

(a) $A = \sqrt{\lambda/\pi}$.
(b) $\langle x \rangle = a$, $\langle x^2 \rangle = \frac{1}{2\lambda} + a^2$, and $\sigma = \frac{1}{\sqrt{2\lambda}}$.
(c) Bell curve at $x = a$ and maximum $\rho(a) = A$.


## Problem 1.5
\color{Black}

Consider the wave function

$$
\Psi(x, t) = A e^{-\lambda|x|} e^{-i\omega t},
$$

where $A$, $\lambda$, and $\omega$ are positive real constants. (We’ll see in Chapter 2 for what potential (V) this wave function satisfies the Schrödinger equation.)
(a) Normalize $\Psi$.
(b) Determine the expectation values of $x$ and $x^2$ .
(c) Find the standard deviation of $x$. Sketch the graph of $|\Psi|^2$, as a function of $x$, and mark the points ($\langle x \rangle + \sigma$) and ($\langle x \rangle - \sigma$), to illustrate the sense in which $\sigma$ represents the "spread" in x. What is the robability that the particle would be found outside this range?

### Solution (1.5)
\color{Blue}

(a) $A = \sqrt{\lambda}$.
(b) $\langle x \rangle = 0$, $\langle x^2 \rangle = \frac{1}{2\lambda^2}$.
(c) $\sigma = \frac{1}{\sqrt{2}\lambda}$. $P(|x| > \sigma) = e^{-\lambda}$.


## Problem 1.8
\color{Black}

Suppose you add a constant $V_0$ to the potential energy (by "constant" I mean
independent of $x$ as well as $t$). In classical mechanics this doesn’t change anything, but
what about quantum mechanics? Show that the wave function picks up a time-dependent
phase factor: $\exp(−i V_0 t /\hbar)$. What effect does this have on the expectation value of a dynamical variable?

### Solution (1.8)
\color{Blue}

No effect.
